spring:
  application:
    name: spring-boot-mongo-web-flux
  data:
    mongodb:
      database: mongo
      host: localhost
      port: 27017
      username: user
      password: password
server:
  port: 8080